// missions-t6.js — Tropico 6 mission data (30 missions)

const MISSIONS_T6 = [
  // ── Base Game ─────────────────────────────────────────────
  {
    id: 1,
    name: "Penultimo of the Caribbean",
    era: "Colonial",
    type: "Base Game",
    desc: "The introductory mission. Lord Roger Wyndham of the Crown demands a Sugar Plantation and Rum Distillery. Penultimo appears with a cunning plan: set up a Coconut Harvester, run a Pirate Cove, and smuggle gold inside coconuts (Goldnuts) past the suspicious — but coconut-allergic — Lord Wyndham. Build Guard Towers, win the people's support, and proclaim independence from the Crown.",
  },
  {
    id: 2,
    name: "Good Morning, Mr. President",
    era: "Cold War",
    type: "Base Game",
    desc: "El Presidente is awakened each morning by a different faction or foreign power with an urgent demand. Manage a cascade of overlapping requests from the Eastern Bloc, Western Powers, militarists, communists, and more — balancing their competing interests while keeping approval high enough to survive re-election.",
  },
  {
    id: 3,
    name: "Whack-a-Mole",
    era: "Modern",
    type: "Base Game",
    desc: "Political opponents keep emerging like whack-a-moles in the modern media landscape. Use a combination of edicts, media buildings, secret agents, and presidential authority to keep dissent under control while maintaining a democratic façade for foreign powers.",
  },
  {
    id: 4,
    name: "Meltdown at the Rio Grande",
    era: "Modern",
    type: "Base Game",
    desc: "Tensions along the border between Tropico and its neighbours have reached a boiling point. El Presidente must navigate a diplomatic crisis, manage refugee flows, and decide how to respond to outside pressure — all while keeping the island's economy and faction relations from collapsing.",
  },
  {
    id: 5,
    name: "Revolution 1.5",
    era: "World Wars",
    type: "Base Game",
    desc: "Tropico is in the grip of revolutionary fervour during the turbulent World Wars era. El Presidente must manage rising rebel sentiment, please the Axis and Allies simultaneously, and build a strong enough nation to survive the revolution — or quietly direct it to a favourable outcome.",
  },
  {
    id: 6,
    name: "Oil",
    era: "Modern",
    type: "Base Game",
    desc: "Black gold is discovered beneath Tropico's waters. El Presidente must build an oil industry from scratch, navigate the geopolitical pressures of foreign powers eager to control the resource, and use the petro-wealth to modernise the island without destroying the environment or upsetting the populace.",
  },
  {
    id: 7,
    name: "Bleep!",
    era: "Cold War",
    type: "Base Game",
    desc: "Information control is the name of the game during the Cold War. El Presidente wields censorship edicts, surveillance buildings, and media manipulation to shape public perception — while foreign intelligence agencies compete to expose what's really happening on the island.",
  },
  {
    id: 8,
    name: "Cement Shoes",
    era: "World Wars",
    type: "Base Game",
    desc: "Organised crime has taken root on Tropico during the chaotic World Wars era. Build up law enforcement, root out criminal elements, and keep the wartime economy afloat — all while the Allies and Axis watch closely, each offering their own brand of 'help'.",
  },

  // ── DLC Standalone Missions ───────────────────────────────
  {
    id: 9,
    name: "The Llama of Wall Street",
    era: "Modern",
    type: "DLC",
    dlc: "The Llama of Wall Street",
    desc: "Enter the world of big business. New Trade Institute mechanics let El Presidente forecast market trends, trigger price fluctuations, and play global commodity markets. Random economic events create positive, negative, or chaotic effects on trade — master the market or be crushed by it.",
  },
  {
    id: 10,
    name: "Yachts for El Presidente",
    era: "Modern",
    type: "DLC",
    dlc: "Tropican Shores",
    desc: "Navigate Tropico's luxurious new era of offshore expansion. Build Submarine Tours, dock a Tropitanic, offer Dolphin Therapy, and manage the island's new Pearl economy — all while collecting the rewards of ruling the waves as well as the land.",
  },
  {
    id: 11,
    name: "El Árbol De Maravilla",
    era: "Modern",
    type: "DLC",
    dlc: "Return to Nature",
    desc: "Build a greener Tropico. Construct Forest Schools, Tree Houses, and the iconic Biggdrasil — the island's first homegrown world wonder and the first one El Presidente can customize. Raise the new Nature value and impress Sunny Flowers with your commitment to a sustainable paradise.",
  },

  // ── Caribbean Skies Campaign ──────────────────────────────
  {
    id: 12,
    name: "Caribbean Skies — Mission 1",
    era: "Modern",
    type: "DLC",
    dlc: "Caribbean Skies",
    desc: "The first mission of the Caribbean Skies drone campaign. New drone technology arrives on Tropico — Delivery Drones, Drone Taxis, and Security Drones change how the island is managed. Meet new characters and start your mission to save the world, El Presidente-style.",
  },
  {
    id: 13,
    name: "Caribbean Skies — Mission 2",
    era: "Modern",
    type: "DLC",
    dlc: "Caribbean Skies",
    desc: "The drone network expands. Use Cargo Airports and Balloon Tours to connect your archipelago more efficiently. A new play style unlocks as the story of the Caribbean Skies campaign develops.",
  },
  {
    id: 14,
    name: "Caribbean Skies — Mission 3",
    era: "Modern",
    type: "DLC",
    dlc: "Caribbean Skies",
    desc: "Further into the Caribbean Skies campaign — drone deliveries, surveillance, and aerial transport reach new heights. El Presidente must use every technological advantage to stay ahead of the emerging crisis.",
  },
  {
    id: 15,
    name: "Caribbean Skies — Mission 4",
    era: "Modern",
    type: "DLC",
    dlc: "Caribbean Skies",
    desc: "The penultimate Caribbean Skies mission. The stakes rise as El Presidente's drone empire is tested. New characters and a developing story push the limits of what Tropico's technology can achieve.",
  },
  {
    id: 16,
    name: "Caribbean Skies — Mission 5",
    era: "Modern",
    type: "DLC",
    dlc: "Caribbean Skies",
    desc: "The finale of the Caribbean Skies campaign. El Presidente must save the world using all the drone-powered tools built across the campaign. The culmination of Tropico's most technologically ambitious adventure.",
  },

  // ── Festival Campaign ─────────────────────────────────────
  {
    id: 17,
    name: "Festival Campaign — Mission 1",
    era: "Modern",
    type: "DLC",
    dlc: "Festival",
    desc: "Boredom — an ancient evil — threatens to engulf Tropico in clouds of mundanity. The only defence: festivals. Build festival areas and supply them with Balloons and Fireworks to drive back the tide of dullness.",
  },
  {
    id: 18,
    name: "Festival Campaign — Mission 2",
    era: "Modern",
    type: "DLC",
    dlc: "Festival",
    desc: "The Festival campaign continues. Manage 20+ festival variations across 4 special areas, each with unique effects — converting knowledge into money, triggering baby booms, and boosting nearby buildings.",
  },
  {
    id: 19,
    name: "Festival Campaign — Mission 3",
    era: "Modern",
    type: "DLC",
    dlc: "Festival",
    desc: "Boredom pushes back harder. El Presidente must escalate the festival empire, unlocking Ticket Booths, Dance Schools, and Balloon Factories to keep the people entertained and the ancient evil at bay.",
  },
  {
    id: 20,
    name: "Festival Campaign — Mission 4",
    era: "Modern",
    type: "DLC",
    dlc: "Festival",
    desc: "The Festival campaign's penultimate chapter. Festival planning becomes strategic — choosing which festival to run, where to place it, and how to maximise its unique effects on the island.",
  },
  {
    id: 21,
    name: "Festival Campaign — Mission 5",
    era: "Modern",
    type: "DLC",
    dlc: "Festival",
    desc: "The Festival campaign finale. Boredom makes its final stand against Tropico's greatest party empire. El Presidente must unleash the full force of the festival machine to defeat the ancient evil once and for all.",
  },

  // ── New Frontiers / Mission Mars Campaign ─────────────────
  {
    id: 22,
    name: "Mission Mars — Mission 1",
    era: "Modern",
    type: "DLC",
    dlc: "New Frontiers",
    desc: "The space race begins. El Presidente competes against international rivals in a research race toward the stars. Build the foundation of a Spaceport Complex and begin recruiting the scientists and resources needed for the Mars mission.",
  },
  {
    id: 23,
    name: "Mission Mars — Mission 2",
    era: "Modern",
    type: "DLC",
    dlc: "New Frontiers",
    desc: "The New Frontiers campaign continues. Assemble rocket components using the new vertical stacking mechanic in the Spaceport Complex. Meet familiar characters from the Tropico series, including Professor Hector Sanchez.",
  },
  {
    id: 24,
    name: "Mission Mars — Mission 3",
    era: "Modern",
    type: "DLC",
    dlc: "New Frontiers",
    desc: "The race for Mars intensifies. Fuel a Fusion Reactor, manage the Reclaimer, and launch early moon missions to unlock bonuses for the island. The competition is fierce — other nations want to reach Mars first.",
  },
  {
    id: 25,
    name: "Mission Mars — Mission 4",
    era: "Modern",
    type: "DLC",
    dlc: "New Frontiers",
    desc: "El Presidente's Mars ambitions grow. Expand the Mars colony by sending Tropicans into space — getting rid of unwanted citizens while securing valuable resource bonuses for the island. Veronica Veneno and Patch make their appearance.",
  },
  {
    id: 26,
    name: "Mission Mars — Mission 5",
    era: "Modern",
    type: "DLC",
    dlc: "New Frontiers",
    desc: "The Mission Mars finale. Lead Tropico into a glorious future by winning the international space race. Launch the final mission to Mars and establish Tropico's permanent colony on the red planet.",
  },

  // ── Going Viral Campaign ──────────────────────────────────
  {
    id: 27,
    name: "Going Viral — Mission 1",
    era: "Modern",
    type: "DLC",
    dlc: "Going Viral",
    desc: "The first disease strikes Tropico. El Presidente must manage the new Panic mechanic — high panic unlocks powerful edicts, but risks social breakdown. Use the Healing Howitzer, Medical Checkpoints, and Ambrosius Quack's Magic Hut to find the cure.",
  },
  {
    id: 28,
    name: "Going Viral — Mission 2",
    era: "Modern",
    type: "DLC",
    dlc: "Going Viral",
    desc: "A second disease outbreak hits the island. Each disease has different effects — some severely harm citizens, others cause mild symptoms. El Presidente must decide: raise the alarm for powerful crisis edicts, or keep the population calm?",
  },
  {
    id: 29,
    name: "Going Viral — Mission 3",
    era: "Modern",
    type: "DLC",
    dlc: "Going Viral",
    desc: "Disease number three. The Colossal Hospital and new medical infrastructure are put to the test. Sixteen crisis edicts — mandate masks, viral palace parties, or inject-first approaches — give El Presidente unique ways to exploit the outbreak.",
  },
  {
    id: 30,
    name: "Going Viral — Mission 4",
    era: "Modern",
    type: "DLC",
    dlc: "Going Viral",
    desc: "The Going Viral campaign finale. The fourth and final disease is the most dangerous yet. El Presidente must use every medical building and crisis edict available to save Tropico — or cynically exploit the chaos for maximum personal gain.",
  },
];
