// missions-t4.js — Tropico 4 mission data (42 missions)

const MISSIONS_T4 = [
  // ── Campaign ──────────────────────────────────────────────
  {
    id: 1,
    name: "Rise to Power",
    category: "Campaign",
    island: "Santa Clara",
    desc: "After taking charge of a 'fourth world country' that lacks even the most basic facilities, Generalissimo Santana puts forth a checklist: provide the island's citizens with food, religion, healthcare, housing, and entertainment — then get re-elected.",
  },
  {
    id: 2,
    name: "It's All Mine",
    category: "Campaign",
    island: "Isla de Hierro",
    desc: "El Presidente becomes business partners with Keith Preston, CEO of Fruitas Ltd., and begins mining operations on a dangerously seismic island. An earthquake traps miners underground, and China's 'solution' only makes things worse.",
  },
  {
    id: 3,
    name: "Into the Spotlight",
    category: "Campaign",
    island: "Cara Libro",
    desc: "To gain global recognition, El Presidente develops a newly independent former British colony into a famous tourist destination, then uses it to host a summit meeting between several world leaders.",
  },
  {
    id: 4,
    name: "IMPORTant Business",
    category: "Campaign",
    island: "Yermo Encarnado",
    desc: "Still in partnership with Keith Preston, El Presidente develops a barren island with no natural resources into an international trading port — importing coffee, rum, cigars and industrial goods to build an unlikely economic powerhouse.",
  },
  {
    id: 5,
    name: "Tropico Above All",
    category: "Campaign",
    island: "Isla Desconcida",
    desc: "After Tropico is called 'boring', El Presidente starts breaking world records and topping UN leaderboards. This inadvertently enrages Brunhilde Van Hoof, the vindictive UN official, who raises construction costs in retaliation.",
  },
  {
    id: 6,
    name: "Bickering Factions",
    category: "Campaign",
    island: "Santa Teresa",
    desc: "Amid high political passions and the looming threat of violent rebellion from Marco Moreno, El Presidente must choose sides four times between rival factions — Capitalists vs. Communists, Intellectuals vs. Militarists, Environmentalists vs. Religious, Loyalists vs. Nationalists.",
  },
  {
    id: 7,
    name: "Crisis",
    category: "Campaign",
    island: "Pachanga Volcánica",
    desc: "Caught in the middle of a Cold War missile crisis, El Presidente must keep global DEFCON from hitting 1. When the US president is assassinated by an agent claiming to work for Tropico, the presidente must flee the island under a new identity.",
  },
  {
    id: 8,
    name: "Survival",
    category: "Campaign",
    island: "Isla Oscura",
    desc: "Under a new identity, El Presidente takes control of a former penal colony turned smuggling port and must hunt down and eliminate three heads of the island's crime families — Don Aemillio, Donna Bella, and Don Moriarti.",
  },
  {
    id: 9,
    name: "No One Left Behind",
    category: "Campaign",
    island: "Nueva Esperanza",
    desc: "El Presidente heads to an underpopulated island with the intention of making money by accepting all the world's disenfranchised people — mimes, cold-hearted lawyers, telephone hygienists, starving artists, former pirates, and circus rejects.",
  },
  {
    id: 10,
    name: "Independence Day",
    category: "Campaign",
    island: "Isla Desconcida",
    desc: "El Presidente hatches a plan to get Europe to reaccept a backwater island as a colonial territory. Once the island is developed with the EU's help, the presidente works with the USSR to start a revolution and declare independence.",
  },
  {
    id: 11,
    name: "Fruity Business",
    category: "Campaign",
    island: "Puerto Angélico",
    desc: "Now that El Presidente has reestablished a power base, thoughts turn to revenge against conspirator Keith Preston. By developing an island into an agricultural powerhouse, El Presidente becomes majority shareholder of Fruitas Ltd. — and fires Keith from his own company.",
  },
  {
    id: 12,
    name: "The Olympic Heist",
    category: "Campaign",
    island: "Isla Tropicana",
    desc: "After being fired from Fruitas Ltd., Keith Preston invests nearly all his money into the top three Olympic host contenders. To ruin him completely, El Presidente makes Tropico the main contender for the Olympic Games, bankrupting Keith in the process.",
  },
  {
    id: 13,
    name: "The Blind Revolution",
    category: "Campaign",
    island: "Nueva Esperanza",
    desc: "El Presidente turns attention to Marco Moreno, who was manipulated into opposing their rule. To win Marco over, the presidente must either demonstrate dedication to the people (healthcare, housing, literacy) or impress him with military might (soldiers, army bases, nuclear program).",
  },
  {
    id: 14,
    name: "To Bait Fish Withal",
    category: "Campaign",
    island: "Isla Oscura",
    desc: "Generalissimo Santana discovers El Presidente's identity and captures their 'twin', using both to blackmail the presidente into servitude. Meanwhile, Marco Moreno infiltrates Santana's island and sparks a rebellion against the generalissimo.",
  },
  {
    id: 15,
    name: "Best Served Cold",
    category: "Campaign",
    island: "Puerto Gato",
    desc: "El Presidente has taken control of Generalissimo Santana's island, forcing him into hiding. But the population remains fiercely loyal to their former leader. El Presidente must dismantle both Santana's rebel force and his underground resistance movement.",
  },
  {
    id: 16,
    name: "Operation Endgame",
    category: "Campaign",
    island: "Costa Laplata",
    desc: "El Presidente becomes a figurehead for an island run by Brunhilde Van Hoof and five equally corrupt UN Inspectors. Each inspector meddles in the island's affairs, enacting unwanted edicts and draining the treasury — the presidente must oust them one by one.",
  },
  {
    id: 17,
    name: "Forgiveness",
    category: "Campaign",
    island: "St. Maria Magnifica",
    desc: "With the truth revealed, El Presidente returns to power in Tropico. But a wave of suspicious 'accidents' — a poisoned food taster, a collapsed construction site, an exploding cigar — leads Penultimo to believe the conspiracy against the presidente isn't over yet.",
  },
  {
    id: 18,
    name: "The Clandestine War",
    category: "Campaign",
    island: "Pachanga Volcánica",
    desc: "After Generalissimo Santana rats out Nick Richards as the conspiracy's mastermind, El Presidente searches for hard evidence. The USSR has exactly what's needed — in exchange for turning Tropico into a luxury resort and luring top American spies to their deaths.",
  },
  {
    id: 19,
    name: "Perestroika",
    category: "Campaign",
    island: "Cara Libro",
    desc: "As a final favour for the USSR, El Presidente uses Tropico as a testing ground for Soviet political reforms — glasnost, free markets, and open diplomacy. All to secure a tape recording that will expose Nick Richards to the world.",
  },
  {
    id: 20,
    name: "Tropican Utopia",
    category: "Campaign",
    island: "Isla de Hierro",
    desc: "With the conspiracy completely destroyed, El Presidente can finally pursue the original dream: creating the greatest country in the world. Minimum wage laws, hospitals, cathedrals, free housing, social security — and three monuments to Tropico's virtues, all by 2012.",
  },

  // ── Modern Times ──────────────────────────────────────────
  {
    id: 21,
    name: "State of Emergency",
    category: "Modern Times",
    island: "Isla de Sentencia",
    desc: "After leaving Penultimo in charge for a year's vacation, El Presidente returns to find the world in crisis and Tropico ruined by Penultimo's spectacular incompetence. Doomsday rumors, a crime wave, an economic collapse — and Brunhilde Van Hoof's new Panic Meter threatening disaster.",
  },
  {
    id: 22,
    name: "The Hiccups",
    category: "Modern Times",
    island: "Isla del Furioso",
    desc: "Tropico becomes the victim of a mysterious plague causing uncontrollable hiccuping. If the number of infected reaches 100, the UN will quarantine the island. Dr. Steinschneider arrives to help, suggesting everything from horror movies to rum cures — with increasingly dire results.",
  },
  {
    id: 23,
    name: "The Truth is Out There",
    category: "Modern Times",
    island: "Isla de Pieta",
    desc: "After Penultimo begins acting suspiciously intelligently, his friends conclude something is very wrong. A hospital examination reveals he's been replaced by a clone. El Presidente must find and free the real Penultimo, then deal with a second virus that turns citizens into Penultimo clones.",
  },
  {
    id: 24,
    name: "The Shakes",
    category: "Modern Times",
    island: "Piedra Island",
    desc: "El Presidente investigates the source of Penultimo's captors on a dangerously volcanic and seismic island. Dr. Steinschneider builds a Doomsday Clock in a volcano, discovers the earthquakes are artificial, and unmasks the secret underground organization known as 'the Conclave'.",
  },
  {
    id: 25,
    name: "Countdown to Oblivion",
    category: "Modern Times",
    island: "Costa del Limbo",
    desc: "Paranoid ex-KGB General Igor Fedorov believes the Conclave is based in Alaska and plans to invade — which would trigger World War 3. El Presidente befriends the general to derail his plans from the inside, while Dr. Steinschneider races to expose the Conclave's true location.",
  },
  {
    id: 26,
    name: "Keep Calm and Carry On",
    category: "Modern Times",
    island: "Tierra de la Venganza",
    desc: "With WW3 averted but the Conclave still active, Dr. Steinschneider theorizes the panic gripping US citizens can be weaponized to shake the Conclave's hold on global affairs. A canned goods index, sheep-powered mind control, and an army of goats are all part of the plan.",
  },
  {
    id: 27,
    name: "War on Terror",
    category: "Modern Times",
    island: "Piedra Island",
    desc: "Though the Conclave is seemingly eliminated, a wave of terrorist attacks sweeps the world. El Presidente must investigate the bombing of the ministry using military, police, or civilian strategies — while media mogul Donald Pynch uses his empire to frame El Diablo for the crimes.",
  },
  {
    id: 28,
    name: "Presidente vs. Zombies",
    category: "Modern Times",
    island: "Costa del Limbo",
    desc: "Donald Pynch offers to cut El Presidente in on his media profits by expanding to Tropico. But strange signals from radio and TV antennas start transforming the islanders into zombies. General Fedorov threatens invasion if the zombies aren't cured before they spread to Russia.",
  },
  {
    id: 29,
    name: "The Earth Warriors",
    category: "Modern Times",
    island: "Isla de Pieta",
    desc: "El Presidente must rule an island dominated by radical environmentalists who are themselves dominated by Donald Pynch's manipulative (and often false) news stories. The 'Earth Warriors Network' demands the destruction of all fishing, power, garbage, and industrial buildings.",
  },
  {
    id: 30,
    name: "The Show Must Go On",
    category: "Modern Times",
    island: "Tierra de la Venganza",
    desc: "Freed from Conclave mind control, Donald Pynch joins El Presidente to build the biggest entertainment empire in the world — a Telecom HQ, designer phones, an 'Angry Toucans' mobile game, and a talent show — all to stop the Conclave's subliminal media takeover.",
  },
  {
    id: 31,
    name: "Before the Storm",
    category: "Modern Times",
    island: "Isla de Sentencia",
    desc: "Dr. Steinschneider faked his own death and used mind-control technology on the Conclave to attempt global domination. El Presidente must secure alliances with the US, USSR, and media empire simultaneously, while the doctor deploys communist rays, resource depleters, and treasury evaporators.",
  },
  {
    id: 32,
    name: "1984",
    category: "Modern Times",
    island: "Fin del Mundo",
    desc: "The Conclave destroys the global economy and starts targeting El Presidente directly with a laser from the moon. The presidente must choose between Donald Pynch's solar reflectors, General Fedorov's space missile, or their own Space Robot / Ziggurat plan to defeat Dr. Steinschneider once and for all.",
  },

  // ── DLC ───────────────────────────────────────────────────
  {
    id: 33,
    name: "The New Sparta",
    category: "DLC",
    island: "Almas Perdidas",
    dlcPack: "Junta",
    desc: "El Presidente has declared war on a neighboring island! Military supporters send money every year, and building a martial economy under constant wartime footing is both the challenge and the reward. Build the mightiest army in the Caribbean.",
  },
  {
    id: 34,
    name: "Plantador",
    category: "DLC",
    island: "Puerto de Oro",
    dlcPack: "Plantador",
    desc: "El Presidente wakes up with amnesia on an eerie island populated by backwoods yokels, and takes charge. Nothing can be built until it's researched first. The mission culminates in constructing six Ferris Wheels to stave off the invasion of Cthulhu.",
  },
  {
    id: 35,
    name: "Gods of Economy",
    category: "DLC",
    island: "Isla Divina",
    dlcPack: "Quick Dry Cement",
    desc: "Housing is the next big thing as El Presidente builds houses for cash — but must keep two temperamental gods happy. A Volcano God unleashes earthquakes when the treasury exceeds $50,000; a Wind God brings tornadoes as 'protest'. Quick Build wisely and appease them both.",
  },
  {
    id: 36,
    name: "Pirate Heaven",
    category: "DLC",
    island: "Isla De Bucanero",
    dlcPack: "Pirate Heaven",
    desc: "El Presidente turns Tropico into a pirate paradise. Balance a Pirate Index against a UNESCO Heritage Index — let the pirate heritage grow too fast and Brunhilde Van Hoof sends an invasion force; reach 100 on the Heritage Index and Tropico is internationally protected.",
  },
  {
    id: 37,
    name: "Megalopolis",
    category: "DLC",
    island: "Tierra de la Luna",
    dlcPack: "Megalopolis",
    desc: "El Presidente enters a competition to create the greatest city in the world. Points are scored by whether citizens have jobs, homes, or both. The real challenge: surpass the city of Norilsk's 20,000 city points before they can outbuild you.",
  },
  {
    id: 38,
    name: "The Masked Avenger",
    category: "DLC",
    island: "Criptonía",
    dlcPack: "Vigilante",
    desc: "El Presidente is secretly the Masked Avenger, a dashing superhero! Choose your origin animal (Llama, Shark, or Toucan), select a superpower, pick a sidekick, then defeat an outbreak of criminals, rebels, and an economic crisis — before Penultimo reveals himself as your arch-nemesis Ultimo.",
  },
  {
    id: 39,
    name: "The Big Voodoo Shuffle",
    category: "DLC",
    island: "Isla Encantada",
    dlcPack: "Voodoo",
    desc: "After the Local Witch Doctor dies under Unusual Circumstances, the evil sorceress Vanya curses Tropico. El Presidente must build a Voodoo Manor, call on spirit guardians (Greed, Sloth, or Pride), summon a Loa to mitigate the curse, and erect a Gold Statue — all within a tight deadline.",
  },
  {
    id: 40,
    name: "Peace, Love, and Understanding",
    category: "DLC",
    island: "Isla de la Verdad",
    dlcPack: "The Academy",
    desc: "Penultimo accidentally rerouted a shipment meant for Isla Guerra to Isla Guerera, triggering an international political crisis. El Presidente installs Penultimo as First Secretary, stages a fake rebel bombing, builds the East Point Academy, amasses 6 generals and 30 soldiers, then fights off a real Marco Moreno assault.",
  },
  {
    id: 41,
    name: "How I Learned to Love the Bomb",
    category: "DLC",
    island: "Isla de Extraño Amor",
    dlcPack: "Apocalypse",
    desc: "Nuclear war is imminent. El Presidente must build a Nuclear Shelter before the year 2000, then convince four rival factions — Communists or Capitalists, Loyalists or Intellectuals, Militarists or Religious, Nationalists or Environmentalists — to enter the bunker without causing a panic.",
  },
  {
    id: 42,
    name: "The Communist Propaganda Competition",
    category: "DLC",
    island: "Isla de Guerra",
    dlcPack: "Propaganda",
    desc: "El Presidente decides that Tropico — not the USSR — has the final say in Communist propaganda. Build propaganda towers to convert citizens to loyal loyalists, then complete seven tasks to prove Tropican communist utopia can make those blatant lies come true.",
  },
];
